version: '3'
services:
  web:
      image: nginx:alpine
      volumes:
          - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
          - "./etc/ssl:/etc/ssl"
          - "./bin:/var/www/html/public"
          - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      ports:
          - "80:80"
      environment:
          - NGINX_HOST=${NGINX_HOST}
      command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      restart: always
      depends_on:
          - php
          - db
  php:
      image: nanoninja/php-fpm:${PHP_VERSION}
      restart: always
      volumes:
          - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
          - "./bin:/var/www/html/public"

  db:
    image: mariadb:latest
    volumes:
      - ./db/data_dump:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass
